version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite+aiosqlite:///./game.db
      - TG_TOKEN=${TG_TOKEN}
      - GROUP_CHAT_ID=${GROUP_CHAT_ID}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    command: bash -c "python bot.py & python worker.py"
